<?php

/**
 * Central Dashboard permission registry.
 * Source of truth for which permissions exist and how they are displayed.
 * Runtime assignments live in the database; this file must not invent unknown names at request time.
 *
 * @return array{
 *     modules: array<string, array{label: string}>,
 *     risk_levels: array<string, array{label: string}>,
 *     permissions: list<array{
 *         name: string,
 *         label: string,
 *         description: string,
 *         module: string,
 *         risk_level: string,
 *         assignable: bool,
 *         protected: bool
 *     }>,
 *     system_roles: list<array{
 *         name: string,
 *         label: string,
 *         description: string,
 *         is_system: bool,
 *         is_protected: bool,
 *         is_assignable: bool,
 *         baseline_permissions: list<string>
 *     }>
 * }
 */
return [
    'modules' => [
        'dashboard' => ['label' => 'لوحة التحكم'],
        'employees' => ['label' => 'الموظفون'],
        'roles' => ['label' => 'الأدوار والصلاحيات'],
        'profiles' => ['label' => 'الملفات الشخصية'],
        'documents' => ['label' => 'الوثائق'],
        'applications' => ['label' => 'طلبات الرخص'],
        'payments' => ['label' => 'المدفوعات'],
        'appointments' => ['label' => 'المواعيد والاختبارات'],
        'licenses' => ['label' => 'الرخص'],
        'fines' => ['label' => 'الغرامات'],
        'audit' => ['label' => 'سجلات التدقيق'],
        'reports' => ['label' => 'التقارير'],
        'settings' => ['label' => 'الإعدادات'],
        'notifications' => ['label' => 'الإشعارات'],
        'ai_agent' => ['label' => 'المساعد الذكي'],
        'citizens' => ['label' => 'المواطنون'],
        'content' => ['label' => 'المحتوى والرسائل'],
    ],

    'risk_levels' => [
        'normal' => ['label' => 'عادي'],
        'sensitive' => ['label' => 'حسّاس'],
        'critical' => ['label' => 'حرج'],
    ],

    'permissions' => [
        [
            'name' => 'access_dashboard',
            'label' => 'الوصول إلى لوحة التحكم',
            'description' => 'الدخول إلى واجهة لوحة التحكم الخاصة بالموظفين.',
            'module' => 'dashboard',
            'risk_level' => 'normal',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_employees',
            'label' => 'إدارة الموظفين',
            'description' => 'إنشاء وتعديل وتفعيل وتعيين أدوار الموظفين.',
            'module' => 'employees',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_employees',
            'label' => 'عرض الموظفين',
            'description' => 'عرض قائمة وبيانات الموظفين دون تعديل.',
            'module' => 'employees',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'create_employees',
            'label' => 'إنشاء موظفين',
            'description' => 'إنشاء حسابات موظفين جديدة.',
            'module' => 'employees',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'update_employees',
            'label' => 'تعديل الموظفين',
            'description' => 'تعديل بيانات حسابات الموظفين.',
            'module' => 'employees',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'disable_employees',
            'label' => 'تعطيل الموظفين',
            'description' => 'تعطيل أو تفعيل حسابات الموظفين.',
            'module' => 'employees',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'reset_employee_passwords',
            'label' => 'إعادة تعيين كلمات مرور الموظفين',
            'description' => 'إعادة تعيين كلمة مرور موظف من لوحة التحكم.',
            'module' => 'employees',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_roles',
            'label' => 'إدارة الأدوار',
            'description' => 'عرض وإدارة أدوار النظام (يتطلب أيضاً صلاحية مدير النظام الفعلي للعمليات الحساسة).',
            'module' => 'roles',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_roles',
            'label' => 'عرض الأدوار',
            'description' => 'عرض قائمة الأدوار والصلاحيات المرتبطة بها.',
            'module' => 'roles',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'assign_roles',
            'label' => 'تعيين الأدوار',
            'description' => 'تعيين الأدوار للموظفين.',
            'module' => 'roles',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_permissions',
            'label' => 'إدارة الصلاحيات',
            'description' => 'إدارة ربط الصلاحيات بالأدوار والموظفين.',
            'module' => 'roles',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'review_profiles',
            'label' => 'مراجعة الملفات الشخصية',
            'description' => 'مراجعة واعتماد أو رفض بيانات الملف الشخصي للمواطنين.',
            'module' => 'profiles',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'review_documents',
            'label' => 'مراجعة الوثائق',
            'description' => 'عرض قائمة مراجعة الوثائق والموافقة أو الرفض ضمن مسار المراجعة فقط.',
            'module' => 'documents',
            'risk_level' => 'normal',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_applications',
            'label' => 'عرض طلبات الرخص',
            'description' => 'الوصول إلى إدارة وعرض طلبات الرخص العامة.',
            'module' => 'applications',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_applications',
            'label' => 'إدارة طلبات الرخص',
            'description' => 'تنفيذ عمليات إدارة على طلبات الرخص.',
            'module' => 'applications',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_payments',
            'label' => 'عرض المدفوعات',
            'description' => 'عرض عمليات الدفع المرتبطة بالطلبات.',
            'module' => 'payments',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_payments',
            'label' => 'إدارة المدفوعات',
            'description' => 'التحقق من المدفوعات وتنفيذ عمليات الإدارة المالية.',
            'module' => 'payments',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_appointments',
            'label' => 'عرض المواعيد',
            'description' => 'عرض مواعيد الاختبارات والجداول.',
            'module' => 'appointments',
            'risk_level' => 'normal',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_appointments',
            'label' => 'إدارة المواعيد',
            'description' => 'إنشاء وتعديل جداول مواعيد الاختبارات.',
            'module' => 'appointments',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'record_test_result',
            'label' => 'تسجيل نتائج الاختبارات',
            'description' => 'تسجيل نتيجة نجاح أو رسوب للاختبارات.',
            'module' => 'appointments',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_licenses',
            'label' => 'عرض الرخص',
            'description' => 'عرض الرخص الصادرة وبياناتها.',
            'module' => 'licenses',
            'risk_level' => 'normal',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'issue_license',
            'label' => 'إصدار الرخص',
            'description' => 'إصدار رخصة قيادة للمواطن المؤهل.',
            'module' => 'licenses',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_licenses',
            'label' => 'إدارة الرخص',
            'description' => 'حظر وإلغاء حظر الرخص وعمليات الإدارة المرتبطة.',
            'module' => 'licenses',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_fines',
            'label' => 'عرض الغرامات',
            'description' => 'عرض سجلات الغرامات.',
            'module' => 'fines',
            'risk_level' => 'normal',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_fines',
            'label' => 'إدارة الغرامات',
            'description' => 'إنشاء وتعديل ومتابعة الغرامات.',
            'module' => 'fines',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_audit_logs',
            'label' => 'عرض سجلات التدقيق',
            'description' => 'الاطلاع على سجلات التدقيق الأمنية والتشغيلية.',
            'module' => 'audit',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_reports',
            'label' => 'عرض التقارير',
            'description' => 'الوصول إلى تقارير وإحصاءات لوحة التحكم.',
            'module' => 'reports',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_settings',
            'label' => 'إدارة الإعدادات',
            'description' => 'تعديل إعدادات النظام وأنواع الرخص والرسوم.',
            'module' => 'settings',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_notifications',
            'label' => 'عرض الإشعارات',
            'description' => 'عرض إشعارات النظام الإدارية.',
            'module' => 'notifications',
            'risk_level' => 'normal',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'send_notifications',
            'label' => 'إرسال الإشعارات',
            'description' => 'إرسال إشعارات للمستخدمين.',
            'module' => 'notifications',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_ai_agent_logs',
            'label' => 'عرض سجلات المساعد الذكي',
            'description' => 'مراقبة سجلات محادثات المساعد الذكي.',
            'module' => 'ai_agent',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_ai_agent_reports',
            'label' => 'عرض تقارير المساعد الذكي',
            'description' => 'عرض تقارير استخدام المساعد الذكي.',
            'module' => 'ai_agent',
            'risk_level' => 'sensitive',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_users',
            'label' => 'إدارة المواطنين',
            'description' => 'عرض وإدارة حسابات المواطنين من لوحة التحكم.',
            'module' => 'citizens',
            'risk_level' => 'critical',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'view_contact_messages',
            'label' => 'عرض رسائل التواصل',
            'description' => 'عرض رسائل نموذج التواصل.',
            'module' => 'content',
            'risk_level' => 'normal',
            'assignable' => true,
            'protected' => false,
        ],
        [
            'name' => 'manage_contact_messages',
            'label' => 'إدارة رسائل التواصل',
            'description' => 'تحديث حالة رسائل نموذج التواصل.',
            'module' => 'content',
            'risk_level' => 'normal',
            'assignable' => true,
            'protected' => false,
        ],
    ],

    /*
     | Baseline role definitions used by bootstrap for *missing* roles only.
     | Existing Dashboard-managed permission pivots are never overwritten by normal seeding.
     */
    'system_roles' => [
        [
            'name' => 'super_admin',
            'label' => 'مدير النظام العام',
            'description' => 'صلاحيات كاملة عبر تجاوز محمي في الخادم.',
            'is_system' => true,
            'is_protected' => true,
            'is_assignable' => true,
            'baseline_permissions' => ['*'],
        ],
        [
            'name' => 'admin',
            'label' => 'مدير النظام',
            'description' => 'مدير نظام بصلاحيات كاملة عبر التجاوز المحمي.',
            'is_system' => true,
            'is_protected' => true,
            'is_assignable' => true,
            'baseline_permissions' => ['*'],
        ],
        [
            'name' => 'profile_document_reviewer',
            'label' => 'موظف مراجعة الملفات والوثائق',
            'description' => 'مراجعة الملفات الشخصية والوثائق فقط دون إدارة الطلبات العامة.',
            'is_system' => true,
            'is_protected' => false,
            'is_assignable' => true,
            // Intentionally excludes view_applications / manage_applications.
            'baseline_permissions' => [
                'access_dashboard',
                'review_profiles',
                'review_documents',
            ],
        ],
        [
            'name' => 'fines_employee',
            'label' => 'موظف الغرامات',
            'description' => 'إدارة الغرامات وعرض الرخص المرتبطة.',
            'is_system' => true,
            'is_protected' => false,
            'is_assignable' => true,
            'baseline_permissions' => [
                'access_dashboard',
                'view_fines',
                'manage_fines',
                'view_licenses',
            ],
        ],
        [
            'name' => 'audit_employee',
            'label' => 'موظف مراقبة السجلات',
            'description' => 'عرض سجلات التدقيق.',
            'is_system' => true,
            'is_protected' => false,
            'is_assignable' => true,
            'baseline_permissions' => [
                'access_dashboard',
                'view_audit_logs',
            ],
        ],
        [
            'name' => 'reports_employee',
            'label' => 'موظف التقارير',
            'description' => 'عرض تقارير لوحة التحكم.',
            'is_system' => true,
            'is_protected' => false,
            'is_assignable' => true,
            'baseline_permissions' => [
                'access_dashboard',
                'view_reports',
            ],
        ],
        [
            'name' => 'settings_employee',
            'label' => 'موظف الإعدادات',
            'description' => 'إدارة إعدادات النظام ورسائل التواصل.',
            'is_system' => true,
            'is_protected' => false,
            'is_assignable' => true,
            'baseline_permissions' => [
                'access_dashboard',
                'manage_settings',
                'view_contact_messages',
                'manage_contact_messages',
            ],
        ],
        [
            'name' => 'application_manager',
            'label' => 'موظف إدارة الطلبات',
            'description' => 'عرض وإدارة طلبات الرخص.',
            'is_system' => true,
            'is_protected' => false,
            'is_assignable' => true,
            'baseline_permissions' => [
                'access_dashboard',
                'view_applications',
                'manage_applications',
            ],
        ],
        [
            'name' => 'test_employee',
            'label' => 'موظف الاختبارات',
            'description' => 'إدارة المواعيد وتسجيل نتائج الاختبارات.',
            'is_system' => true,
            'is_protected' => false,
            'is_assignable' => true,
            'baseline_permissions' => [
                'access_dashboard',
                'view_appointments',
                'manage_appointments',
                'record_test_result',
            ],
        ],
        [
            'name' => 'license_employee',
            'label' => 'موظف إصدار الرخص',
            'description' => 'إصدار وإدارة الرخص مع عرض الطلبات المرتبطة.',
            'is_system' => true,
            'is_protected' => false,
            'is_assignable' => true,
            'baseline_permissions' => [
                'access_dashboard',
                'view_licenses',
                'issue_license',
                'manage_licenses',
                'view_applications',
            ],
        ],
        [
            'name' => 'payment_employee',
            'label' => 'موظف المدفوعات',
            'description' => 'عرض وإدارة المدفوعات مع عرض الطلبات المرتبطة.',
            'is_system' => true,
            'is_protected' => false,
            'is_assignable' => true,
            'baseline_permissions' => [
                'access_dashboard',
                'view_payments',
                'manage_payments',
                'view_applications',
            ],
        ],
        [
            'name' => 'employee',
            'label' => 'موظف',
            'description' => 'دور موظف عام متعدد المهام (قديم/تشغيلي).',
            'is_system' => true,
            'is_protected' => false,
            'is_assignable' => true,
            'baseline_permissions' => [
                'access_dashboard',
                'review_profiles',
                'review_documents',
                'record_test_result',
                'issue_license',
                'manage_applications',
                'manage_fines',
                'manage_licenses',
            ],
        ],
        [
            'name' => 'citizen',
            'label' => 'مواطن',
            'description' => 'دور حساب المواطن — غير قابل للتعيين لموظفي اللوحة.',
            'is_system' => true,
            'is_protected' => true,
            'is_assignable' => false,
            'baseline_permissions' => [],
        ],
    ],
];
